export const TOKENCONTROL_PENDINGREQUESTS_FETCH =
    'tokenControl/PENDINGREQUESTS_FETCH';
export const TOKENCONTROL_PENDINGREQUESTS_DATA =
    'tokenControl/PENDINGREQUESTS_DATA';
export const TOKENCONTROL_PENDINGREQUESTS_ERROR =
    'tokenControl/PENDINGREQUESTS_ERROR';
export const TOKENCONTROL_BALANCE_FETCH = 'tokenControl/BALANCE_FETCH';
export const TOKENCONTROL_BALANCE_DATA = 'tokenControl/BALANCE_DATA';
export const TOKENCONTROL_BALANCE_ERROR = 'tokenControl/BALANCE_ERROR';
export const TOKENCONTROL_CREATEREQUEST_FETCH =
    'tokenControl/CREATEREQUEST_FETCH';
export const TOKENCONTROL_CREATEREQUEST_DATA =
    'tokenControl/CREATEREQUEST_DATA';
export const TOKENCONTROL_CREATEREQUEST_ERROR =
    'tokenControl/CREATEREQUEST_ERROR';
export const TOKENCONTROL_PAYREQUEST_FETCH = 'tokenControl/PAYREQUEST_FETCH';
export const TOKENCONTROL_PAYREQUEST_DATA = 'tokenControl/PAYREQUEST_DATA';
export const TOKENCONTROL_PAYREQUEST_ERROR = 'tokenControl/PAYREQUEST_ERROR';
export const TOKENCONTROL_CANCELREQUEST_FETCH =
    'tokenControl/CANCELREQUEST_FETCH';
export const TOKENCONTROL_CANCELREQUEST_DATA =
    'tokenControl/CANCELREQUEST_DATA';
export const TOKENCONTROL_CANCELREQUEST_ERROR =
    'tokenControl/CANCELREQUEST_ERROR';
